paths:
  /store/mission:
    post:
      tags:
        - Store
      summary: 가게 미션 작성
      parameters:
      - name: mission
        in: body
        required: true
        schema:
          properties:
            storeId:
              type: bigint
              description: 가게 아이디
              example: 1
            reward:
              type: bigint
              description: 보상 포인트
              example: 500
            deadline:
              type: String
              description: 마감기한
              example: "2024-12-31"
            missionSpec:
              type: String
              description: 내용
              example: "sample mission spec"
      responses:
        '200':
          description: 가게 미션 작성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: 
                  result: 
                    review: 
                      - id: 1
                        reward: 5
                        deadline: "2024-12-31"
                        mission_spec: "sample mission spec"
                        store_id: 1
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: STORE4001
              message:
                type: string
                example: 존재하지 않는 가게입니다.


        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.